### ISSUE TITLE
suggest_rules not working?

### ISSUE THREAD

**Issue by olavtenbosch** [data-cleaning/validatesuggest#8]
suggest_all is not yet contained in the doc?

**Comment by olavtenbosch** [comment]
Got it, it's not suggest_all but the command suggest_rules and it *is* documented

**Comment by olavtenbosch** [comment]
However 'suggest_rules' doesn't seem to work:

> suggest_rules(data)
Error in names(obj) <- names(obj) : 
  invalid to use names()<- on an S4 object of class 'validator'

**Comment by edwindj** [comment]
error mesage was deceiving: it was due to that the set of rules for `suggest_unique` was empty, which was not handles correctly.
